Add new modules
bigbio/quantms pull request #1
Opened 2021-10-28 10:51 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2021-10-30 17:31 UTC, ypriverol requested changes

2021-10-30 17:31 UTC, ypriverol commented on modules/local/decoydatabase/main.nf
> +        container "quay.io/biocontainers/openms:2.6.0--h4afb90d_0"
@daichengxin we need to create an issue that make clears that all these conda should be updated when the dev of 2.7.0 is available.

2021-10-30 17:31 UTC, ypriverol commented on modules/local/decoydatabase/meta.yml
> +    - "@Chengxin Dai"
What is the still of the authors: email? github account?.

2021-10-30 17:31 UTC, ypriverol commented on modules/local/fileconverter/main.nf
> +process FILECONVERTER {
I think this is more like mzML indexing. I suggest the following name: MZMLINDEXING    Opinions @jpfeuffer

2021-10-30 17:31 UTC, ypriverol commented on modules/local/sdrfparsing/main.nf
> +process SDRFPARSING {
SDRFTOOPENMS

2021-10-30 17:31 UTC, ypriverol commented on modules/local/sdrfparsing/main.nf
> +process SDRFPARSING {
@daichengxin if the DIA pipeline will not convert to open MS, then is probably better to keep SDRFPARSING

2021-10-30 17:52 UTC, jpfeuffer commented on modules/local/decoydatabase/main.nf
> +        container "quay.io/biocontainers/openms:2.6.0--h4afb90d_0"
Can we put all openms modules in a subfolder?
openms/$nameofthetool

Maybe even another one for third-party tools

openms/thirdparty/$nameoftheadapter

I bet we can then define shared variables for all those modules in the parent folder

2021-10-30 17:55 UTC, jpfeuffer commented on modules/local/fileconverter/main.nf
> +process FILECONVERTER {
Hmm I could see both sides.
If we generalize it enought I think we should leave it as Fileconverter.
We could then write a wrapper/module/subworkflow around it, that calls it in a way that it only does indexing. And call that step mzmlindexing then.

2021-10-30 17:57 UTC, jpfeuffer commented on modules/local/sdrfparsing/main.nf
> +process SDRFPARSING {
Both is fine for me. Maybe at some point people want to do sdrf to maxquant.

2021-10-30 18:18 UTC, jpfeuffer commented
Wow that was quick. Great work. I will need some time to go over everything.

2021-10-30 22:26 UTC, ypriverol commented on modules/local/fileconverter/main.nf
> +process FILECONVERTER {
I fear is that I don't want to "overcode" if the tool supports more functionalities we should not the module as the tool, we should create modules for functionalities that are in use in the process.

2021-10-30 23:12 UTC, ypriverol commented on modules/local/decoydatabase/main.nf
> +        container "quay.io/biocontainers/openms:2.6.0--h4afb90d_0"
Can you send and example @jpfeuffer about how to do shared variables.

2021-10-31 01:03 UTC, daichengxin commented on modules/local/decoydatabase/main.nf
> +        container "quay.io/biocontainers/openms:2.6.0--h4afb90d_0"
ok, I will create an issue to illustrate version. Putting all openms modules in a subfolder is a good idea. For shared variables, I think we can define them in modules.config file

2021-10-31 01:03 UTC, daichengxin commented on modules/local/decoydatabase/meta.yml
> +    - "@Chengxin Dai"
github accout

2021-10-31 01:20 UTC, daichengxin commented
I am also learning DSL2, and many codes may be optimized and corrected.

2021-10-31 09:05 UTC, ypriverol commented on modules/local/decoydatabase/meta.yml
> +    - "@Chengxin Dai"
If is the GitHub account, your account is @daichengxin 😃

2021-10-31 09:10 UTC, daichengxin commented on modules/local/decoydatabase/meta.yml
> +    - "@Chengxin Dai"
Got it! @ypriverol

2021-11-01 21:10 UTC, ypriverol approved these changes

2021-11-01 22:24 UTC, merged