minor fix
bigbio/quantms pull request #135
Opened 2022-03-22 14:42 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker` --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-03-22 15:05 UTC, jpfeuffer requested changes
My fault, when I suggested changes I didnt see that multiple config files are generated.

2022-03-22 15:05 UTC, jpfeuffer commented on modules/local/generate_diann_cfg/meta.yml
> +description: A module to generate a DIA-NN configuration files, based on input files and params.
```suggestion
description: A module to generate DIA-NN configuration files, based on input files and params.
```

2022-03-22 15:05 UTC, jpfeuffer commented on modules/local/generate_diann_cfg/meta.yml
> +            A custom module to generate a DIA-NN configuration files from input files and params.
```suggestion
            A custom module to generate DIA-NN configuration files from input files and params.
```

2022-03-22 15:05 UTC, jpfeuffer commented on modules/local/librarygeneration/main.nf
> +    path "*.speclib"
Cool looks better. How are the speclib used later, if they do not have an emit: ?

2022-03-23 06:24 UTC, ypriverol approved these changes

2022-03-23 06:25 UTC, merged