Major fix
bigbio/quantms pull request #145
Opened 2022-03-25 08:36 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-03-25 10:02 UTC, jpfeuffer requested changes

2022-03-25 10:02 UTC, jpfeuffer commented on nextflow_schema.json
> +                "epifany_debug": {
They should use the same parameter. They are an either/or

2022-03-25 10:02 UTC, jpfeuffer commented on subworkflows/local/phosphoscoring.nf
> +    IDSCORESWITCHERFORLUCIPHOR(id_files.combine(Channel.value("\"Posterior Error Probability\"")))
was this change tested? you can use the new uploaded test data.

2022-03-25 10:02 UTC, jpfeuffer commented on subworkflows/local/phosphoscoring.nf
> +    IDSCORESWITCHERFORLUCIPHOR(id_files.combine(Channel.value("\"Posterior Error Probability\"")))
was this change tested? you can use the new uploaded test data.

2022-03-25 10:03 UTC, jpfeuffer commented on conf/modules.config
> -                "-new_score_type Posterior Error Probability"
ah yes, to the channel right?

2022-03-25 10:05 UTC, jpfeuffer commented on nextflow_schema.json
> +                "epifany_debug": {
this and proteininference

2022-03-25 11:02 UTC, daichengxin commented on conf/modules.config
> -                "-new_score_type Posterior Error Probability"
Yes

2022-03-25 11:33 UTC, jpfeuffer commented
Linting still fails. You might be able to just do `prettier -m` if you have prettier installed.

2022-03-26 10:34 UTC, jpfeuffer commented
Nice. How did you fix the testdata?

2022-03-27 06:21 UTC, daichengxin commented
Without fixing test_localize testdata .Network issues?

2022-03-27 10:44 UTC, jpfeuffer approved these changes

2022-03-27 13:47 UTC, merged