add MSstatsTMT and update MSstats
bigbio/quantms pull request #158
Opened 2022-04-22 14:24 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
  - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
  - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-04-22 16:06 UTC, jpfeuffer requested changes

2022-04-22 16:06 UTC, jpfeuffer commented on nextflow.config
> +    msstats_tmt_remove_one_feat_prot    = true
I think we should either remove the msstats prefix for all parameters (and group them nicely in the param.json)
or we should use a consistent prefix:
msstats for general, msstatslfq for lfq specific and msstatstmt/iso for iso.

2022-04-22 16:06 UTC, jpfeuffer commented on nextflow.config
> +    skip_post_msstats                           = false
we dont need two skip parameters unless you want to support mixed designs in the near future.

2022-04-22 16:06 UTC, jpfeuffer commented on nextflow.config
> +    msstats_keep_feats_with_few_measurements    = false
Can't you unify this with `msstatstmt_rmpsm_withfewmea_withinrun`.
Should be the same, no?
What about the summary method, do we need two summary method parameters?

2022-04-23 06:33 UTC, ypriverol commented
@daichengxin MSstats is failing with DIANN

2022-04-23 06:34 UTC, daichengxin commented
ok. I am testing locally.

2022-04-23 06:36 UTC, ypriverol commented
I think is because in the last tests we have included only two files in the DIANN with no multiple conditions. But this is only a guess.

2022-04-23 06:40 UTC, daichengxin commented on nextflow.config
> +    msstats_keep_feats_with_few_measurements    = false
There is a difference between these two parameters. One is across run. The other is in withinrun.  For summary method. LFQ options include TMP and `linear`. But ISO includes `msstats` `medianPolish` `Median` `LogSum`.

2022-04-23 07:00 UTC, daichengxin commented
Yes. you are right. I use two conditions locally to test. Need to update the test data

2022-04-23 09:36 UTC, daichengxin commented on nextflow.config
> +    skip_post_msstats                           = false
done

2022-04-23 11:22 UTC, daichengxin commented
The test passed. Need to upload the latest dia test data to nfcore, then recover test_dia config. https://raw.githubusercontent.com/daichengxin/quantms/dev/assets/PXD026600.sdrf.tsv

2022-04-26 07:01 UTC, jpfeuffer commented
Why are you not using the newest version with argument parsing? Because of the additional dependency?
https://github.com/nf-core/proteomicslfq/blob/dev/bin/msstats_plfq.R

2022-04-26 07:06 UTC, daichengxin commented
Yes. `argparse` is not in the container

2022-04-26 08:49 UTC, jpfeuffer commented on bin/msstats_plfq.R
> +    stop("At least the first one argument must be supplied (input csv).n", call.=FALSE)
```suggestion
    stop("At least the first argument must be supplied (input csv).n", call.=FALSE)
```

2022-04-26 08:51 UTC, jpfeuffer commented on bin/msstats_tmt.R
> +    stop("At least the first one argument must be supplied (input csv).n", call.=FALSE)
```suggestion
    stop("At least the first argument must be supplied (input csv).n", call.=FALSE)
```

2022-04-26 08:52 UTC, jpfeuffer commented
Can we maybe have the logging changes separate? I don't think this is ready for release.

2022-04-26 08:56 UTC, jpfeuffer commented
E.g. it needs a lot of testing, the testdata needs to be on nf-core, I think it is better to only have one MSstats step (we need to check whether there are more parameters that we can combine).

2022-04-26 12:15 UTC, daichengxin commented
So do we need to remove the logging changes in this PR?

2022-04-26 12:16 UTC, jpfeuffer commented
No but create a PR with just the logging changes.

2022-04-26 12:16 UTC, jpfeuffer commented
Use `git cherry-pick` on a new branch

2022-04-27 13:16 UTC, ypriverol commented
Can I merge this PR @jpfeuffer ?

2022-04-27 13:20 UTC, ypriverol commented
We need two different PRs? Why we can combine both changes here if they are correct.

2022-04-27 13:26 UTC, ypriverol commented
But @daichengxin changed the MSstats as requested, then both things are OK now.

2022-04-27 13:27 UTC, jpfeuffer commented
> E.g. it needs a lot of testing, the testdata needs to be on nf-core, I think it is better to only have one MSstats step/script (we need to check whether there are more parameters that we can combine).

2022-04-27 13:33 UTC, jpfeuffer commented
You can contribute to this PR. I just want to merge into master soon, and do not want to have half-ready PRs in there.

2022-04-29 09:04 UTC, daichengxin commented
I got the changes that needs to be done.  But I'm afraid I won't be able to do it soon because I'm not very familiar with the mechanics of CI.

2022-04-29 09:38 UTC, merged