Add LFQ part and fixed bugs
bigbio/quantms pull request #20
Opened 2021-11-17 07:32 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2021-11-17 21:08 UTC, ypriverol requested changes

2021-11-17 21:08 UTC, ypriverol commented on modules/local/openms/proteomicslfq/main.nf
> +    ProteomicsLFQ \\
@daichengxin in the proteomicsLFQ the script is also allowed the `-picked_fdr $params.picked_fdr` can enable it by default. @jpfeuffer can you confirm this. It is the same option that you have now in proteininference in the tmt part.

2021-11-18 02:47 UTC, daichengxin commented on modules/local/openms/proteomicslfq/main.nf
> +    ProteomicsLFQ \\
-picked_proteinFDR?

2021-11-18 06:54 UTC, ypriverol commented on modules/local/openms/proteomicslfq/main.nf
> +    ProteomicsLFQ \\
Yes

2021-11-18 07:49 UTC, ypriverol approved these changes

2021-11-18 07:49 UTC, merged