fixed bugs
bigbio/quantms pull request #234
Opened 2022-10-20 14:20 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-10-20 14:28 UTC, jpfeuffer commented on workflows/dia.nf
>      log.info "DIANNCONVERT is based on the output of DIA-NN 1.8.1, other versions of DIA-NN do not support mzTab conversion."
Do you know, if we could print this from inside a step? I saw it written even with DDA which might be a bit confusing.

2022-10-20 14:28 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
Can you explain why we cannot set an ID that would be unique instead?

2022-10-21 06:26 UTC, daichengxin commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
The id of each `meta` is different. But we only get the parameter values once. When `unique` or `first` is used, the first run may return meta=[id:1,.. ] but when run again with `resume`, it may return meta=[id:2,...], possibly due to parallel mechanism. So there is no cache success and it is recognized by nextflow as a new run. 
I don't know if I explained it clearly :joy:

2022-10-21 09:09 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
Where is meta.id set? Do we have control? Then we can just set it to a unique value per experiment.

2022-10-21 10:59 UTC, ypriverol approved these changes

2022-10-21 11:04 UTC, ypriverol requested changes

2022-10-21 11:04 UTC, ypriverol commented on bin/diann_convert.py
> +        seq = seq.replace("X", "")
You have here multiple sequence possibilities, from the top of my head I remember X, B, Z. I think it is better to create a white list including the 22 amino acids. (ARNDBCEQZGHILKMFPSTWYV).

2022-10-21 11:17 UTC, jpfeuffer commented on bin/diann_convert.py
> +        seq = seq.replace("X", "")
The question is also: Is this really completely unknown? Or does it have a mass associated with it as modification for example. Because just counting 0 for an unknown amino acid might be a bit too simple.

2022-10-21 11:21 UTC, daichengxin commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
https://github.com/bigbio/quantms/blob/1ace2fb505a5c79c015041f4739f51d0635aaf08/subworkflows/local/create_input_channel.nf#L76-L78.  It is file name

2022-10-21 11:31 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
But why does it change then??

2022-10-21 11:46 UTC, daichengxin commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
We need to make meta the same for DIA to resume. only use a meta value. see details https://github.com/bigbio/quantms/pull/234#discussion_r1001412808

2022-10-21 11:47 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
I mean, filename should be okay? Why does the filename change so that we cannot use it as an ID?

2022-10-21 12:14 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
Ah you were using the filename of a single mzML to represent the whole experiment? That does not work.
You need to introduce an ID for the experiment as well, so we can access it for steps that consume ALL files together.

2022-10-21 13:20 UTC, ypriverol commented on bin/diann_convert.py
> +        seq = seq.replace("X", "")
In uniprot fasta you don't have anything associated to it. Then we have two options, or we put `null` in the value, or we assume 0 (which is not ideal but is the only way to compute this in mass spec terms).

2022-10-21 14:03 UTC, daichengxin commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
But we still need to remove id, even if the experience id is added. Because different meta channels may be generated at runtime, resulting in cache failure.

2022-10-21 14:06 UTC, daichengxin commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
When I first run, the channel emits meta [id: 1,], but when re-run again, the channel maybe emit meta [id: 2,]

2022-10-21 14:09 UTC, jpfeuffer commented on bin/diann_convert.py
> +        seq = seq.replace("X", "")
But how can DIANN identify it then?

2022-10-21 14:12 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
Yes I think meta should look like this:
```
[
{mzml_ref: foo, exp_ref: designname, param_a: xyz, param_b:xyz }
{mzml_ref: bar, exp_ref: designname, param_a: xyz, param_b:xyz }
]
```

2022-10-21 14:13 UTC, ypriverol commented on bin/diann_convert.py
> +        seq = seq.replace("X", "")
I have no idea. @vdemichev How DIANN handles the unknown sequences in Uniprot, for example peptides with `X`. I mean to compute the theoretical mass for example.

2022-10-21 14:27 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
Or we just use param.input as tag for those steps.

2022-10-21 14:28 UTC, jpfeuffer commented on workflows/dia.nf
> +// remove meta.id to make sure cache identical HashCode
Maybe we can rename id to mzml_id or mzml_ref, to make it clear what it is for

2022-10-21 14:48 UTC, vdemichev commented on bin/diann_convert.py
> +        seq = seq.replace("X", "")
X is interpreted as selenomethionine, an unknown symbol like '*' would be interpreted as either zero mass or glycine, not sure. In general, behaviour on nonsense sequences is undefined.

2022-10-22 06:36 UTC, ypriverol commented on bin/diann_convert.py
> +        seq = seq.replace("X", "")
@daichengxin can you change this accordingly.

2022-10-24 12:18 UTC, jpfeuffer approved these changes

2022-10-24 12:34 UTC, ypriverol approved these changes

2022-10-24 13:12 UTC, merged