enable spectra_ref in mzTab
bigbio/quantms pull request #240
Opened 2022-11-03 13:17 UTC by WangHong007

2022-11-03 14:09 UTC, ypriverol commented
@WangHong007 the `PythonBlack` is failing can you fix that error.

2022-11-03 14:14 UTC, WangHong007 commented
got it @ypriverol

2022-11-03 14:16 UTC, ypriverol commented
@WangHong007 Another error https://github.com/bigbio/quantms/actions/runs/3385995591/jobs/5624826886

2022-11-03 18:23 UTC, jpfeuffer requested changes
In general I saw that you are using chunking to load the mzml info CSV.
Is it really that big or slow? I think we should:
- speed up the code. Use less appends,  less for loops, less string data
- write one file per mzml or even per mzml+level

2022-11-03 18:23 UTC, jpfeuffer commented on bin/mzml_statistics.py
> +    file_columns = ["File_Name", "SpectrumID", "MSLevel", "Charge", "MS2_peaks", "Base_Peak_Intensity", "Retention_Time", "Exp_Mass_To_Charge"]
Not sure if that works without an update in pmultiqc.

2022-11-04 01:33 UTC, WangHong007 commented on bin/mzml_statistics.py
> +            rt = i.getRT() if i.getRT() else np.nan
>     * speed up the code. Use less appends,  less for loops, less string data
This is about mzml_statistics.py or diann_convert.py?
>     * write one file per mzml or even per mzml+level
Will do.
> What about MS3 ?
Does MS3 have the same attributes as MS2? If so, it can be included in the statement block of MS2 when determining the MSLevel.

2022-11-04 07:58 UTC, jpfeuffer commented on bin/mzml_statistics.py
> +            rt = i.getRT() if i.getRT() else np.nan
The first comment was about the reading of mzml_info in pmultiqc.

You will usually only have MS3 in TMT. It  is similar to MS2 but often has multiple precursors. Not sure if there are important QC metrics on them. We can do it later.

2022-11-04 09:14 UTC, WangHong007 commented on bin/mzml_statistics.py
> +            rt = i.getRT() if i.getRT() else np.nan
Now we only count the `spectrum id` and `retention time` of MS3 (same as  MS1). It will also be recorded in the corresponding *_mzml_info.tsv

2022-11-07 15:14 UTC, jpfeuffer commented
Comments are basically addressed but I think pmultiqc needs to be updated now to make the tests pass?

2022-11-07 15:16 UTC, ypriverol commented
https://github.com/bigbio/quantms/pull/241

2022-11-07 15:27 UTC, WangHong007 commented
@ypriverol got it.

2022-11-08 12:54 UTC, ypriverol approved these changes

2022-11-08 13:23 UTC, merged