Major update of latest template from nf-core
bigbio/quantms pull request #262
Opened 2023-03-07 14:49 UTC by ypriverol

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-03-07 15:04 UTC, jpfeuffer commented
I like it better if we have one PR for template merge. And one PR for version update.

2023-03-07 15:47 UTC, jpfeuffer commented
but template update is already merged.

2023-03-07 15:47 UTC, jpfeuffer commented
please pull from upstream

2023-03-07 16:46 UTC, jpfeuffer commented
All tests fail.
We need to fix:
- conda
- proteininference in TMT. Did no one adapt FDRs or something?
- dumpsoftwareversions not working anymore
- multiqc with DIA not working

2023-03-07 17:16 UTC, ypriverol commented
We will take care of all the issues @daichengxin @WangHong007

2023-03-07 18:23 UTC, ypriverol commented
> All tests fail. We need to fix:
> 
> * conda
I will take care of this one 
> * proteininference in TMT. Did no one adapt FDRs or something?
I guess this is a more complex issue @jpfeuffer. Did we change anything in thw TMT algorithm? 
> * dumpsoftwareversions not working anymore
@daichengxin can you take carw of this ☝️
> * multiqc with DIA not working
@WangHong007 can you check why DIA is not working

2023-03-07 19:38 UTC, jpfeuffer commented
I think I saw that the test was failing before the update already.

2023-03-08 01:10 UTC, WangHong007 commented
@ypriverol @jpfeuffer In all DIA test, the identification and quantification work was skipped, and Dia-NN did not work, which caused pmultiqc not to receive the diann_report and mistook it for the DDA type.

2023-03-08 01:22 UTC, ypriverol commented
We should run the identification and quant steps.

2023-03-08 09:33 UTC, jpfeuffer commented
@ypriverol can you maybe do a new PR where you are just changing the version numbers. a) this will have a much cleaner commit history and b) we can be more sure about errors caused by this

2023-03-08 11:12 UTC, ypriverol commented
@jpfeuffer @WangHong007 @daichengxin are working already in the PR.

2023-03-08 11:14 UTC, jpfeuffer commented
Ok. I just think you would save some time. Because most of the errors are not present on nf-core.

2023-03-08 11:14 UTC, jpfeuffer commented
So I think the reason is the very complicated merge in this PR.

2023-03-08 12:18 UTC, daichengxin commented
Hi @jpfeuffer, All issues are solved except for TMT. I tested TMT locally, it also reported same problems. But I tested it using openms 2.8.0, it's ok.  These are two proteininference input files from openms 2.8.0 and  2.9.0. Could you review? Thanks a lot.
2.9.0
[ID_mapper_merge.zip](https://github.com/bigbio/quantms/files/10920427/ID_mapper_merge.zip)
2.8.0
[ID_mapper_merge.zip](https://github.com/bigbio/quantms/files/10920541/ID_mapper_merge.zip)

2023-03-08 13:05 UTC, jpfeuffer commented
We probably need the idXMLs that were used in IDMapper.

2023-03-08 13:10 UTC, daichengxin commented
[TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210_.zip](https://github.com/bigbio/quantms/files/10920892/TMT_Erwinia_1uLSike_Top10HCD_isol2_45stepped_60min_01-20141210_.zip)

2023-03-08 13:14 UTC, timosachsenberg commented
thanks I will look into it immediately

2023-03-08 14:06 UTC, timosachsenberg commented
fixed in https://github.com/OpenMS/OpenMS/pull/6758

2023-03-13 16:44 UTC, jpfeuffer requested changes
Pyopenms was not updated since bioconda is bugged.

2023-03-13 16:44 UTC, jpfeuffer commented on CHANGELOG.md
> +| `openms`              | 2.9.0      |
291

2023-03-13 19:22 UTC, ypriverol commented
@jpfeuffer we are ready. You can merge the PR.

2023-03-13 20:02 UTC, jpfeuffer approved these changes
I hope merging is gonna be fine since it's a messy PR that somehow still shows the template changes. But other than that, looks good.

2023-03-13 20:04 UTC, merged