Add input subworkflow
bigbio/quantms pull request #3
Opened 2021-11-02 08:11 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2021-11-02 10:37 UTC, jpfeuffer commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
Hmm I am not sure if you need to validate "input". 
Because this would most probably be in the general template as well.

2021-11-02 10:54 UTC, daichengxin commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
ok, I will delete this and the code related to genetic data

2021-11-02 10:55 UTC, jpfeuffer commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
https://github.com/bigbio/quantms/blob/dev/lib/WorkflowMain.groovy#L76

2021-11-02 10:55 UTC, jpfeuffer commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
The check is here.

2021-11-02 10:56 UTC, ypriverol commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
I think this is still the default code generated by nf-core. @jpfeuffer

2021-11-02 10:57 UTC, jpfeuffer commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
Yes but not the change to input. We should change it to "database" or whatever other parameters are required.

2021-11-02 11:08 UTC, daichengxin commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
Got it. The input file is validated in WorkflowMain.groovy. The fasta database is validated in WorkflowQuantms. Can we validate the database in WorkflowMain.groovy? Because it's also mandatoy.

2021-11-02 11:09 UTC, jpfeuffer commented on lib/WorkflowQuantms.groovy
> +        if (!params.input) {
Yes, "database" should be checked.

2021-11-04 10:40 UTC, jpfeuffer commented on nextflow.config
> +    nf-core/template Nextflow config file
```suggestion
    nf-core/quantms Nextflow config file
```

2021-11-04 10:41 UTC, jpfeuffer commented on nextflow.config
> +    input                      = "foobarbaz"
one input is enough

2021-11-04 10:42 UTC, jpfeuffer commented on workflows/quantms.nf
> +} else if (tocheck.toLowerCase().endsWith("mzml") || tocheck.toLowerCase().endsWith("raw")) {
I dont think we need to support that anymore. I removed support from plfq as well.
The new style is to have full file paths in the sdrf or the OpenMS experimental design

2021-11-04 10:43 UTC, jpfeuffer commented on workflows/quantms.nf
> +    } else{
Add a TODO that we should validate OpenMS design at some point.

2021-11-04 10:44 UTC, daichengxin commented on workflows/quantms.nf
> +    } else{
Got it

2021-11-04 10:45 UTC, jpfeuffer commented
I think the branching into mzML and raw should be done inside FilePreparation

2021-11-04 10:53 UTC, daichengxin commented
ok. I will do. Thanks  a lot. I will update when I solve the current problems @jpfeuffer

2021-11-04 10:55 UTC, jpfeuffer commented
Cool. I would say we fix those two subworkflows in this PR and then do a new one? Otherwise it gets messy?

2021-11-04 10:57 UTC, daichengxin commented
ok.

2021-11-07 10:20 UTC, ypriverol commented
@daichengxin I think the PR is failing https://github.com/bigbio/quantms/runs/4125431176?check_suite_focus=true because from the python script module (check_sdrf) you are trying to access to a container tool sdrf_pipelines. 

In the previous version of nf-core pipelines, the scripts use to me added into the nf-core container when we built it. Now this is not the case, the containers are call in the module but the code is outside that container. @jpfeuffer do you know what can be done in these cases ? This will always fail unless the check_sdrf is inside the same container that sdrf_pipelines.

2021-11-07 10:25 UTC, daichengxin commented
The strange thing is: I run it successfully with docker in my computer.

2021-11-07 10:31 UTC, ypriverol commented
@daichengxin https://github.com/nf-core/rnaseq/issues/651

2021-11-07 10:33 UTC, daichengxin commented
ohh, Thanks a lot!!!!

2021-11-07 10:43 UTC, daichengxin commented
Hi Yasset, I think I think it is to update the ci.yml file to add this code: `chmod +x  /home/runner/work/quantms/quantms/bin/*`, right? @ypriverol

2021-11-07 10:57 UTC, ypriverol commented
> Hi Yasset, I think it is to update the ci.yml file to add this code: `chmod +x /home/runner/work/quantms/quantms/bin/*`, right? @ypriverol

Can you do `stat bin/check_samplesheet.py` @daichengxin

2021-11-07 12:14 UTC, daichengxin commented
@jpfeuffer @ypriverol  Can you check again? Finally passed.

2021-11-07 12:47 UTC, ypriverol requested changes

2021-11-07 12:47 UTC, ypriverol commented on workflows/quantms.nf
>  // Validate input parameters
I recommend to call this file tmt.nf. The idea that we agreed already is to move proteomicslfq into this workflow to reuse efforts, modules, code etc.

2021-11-07 12:58 UTC, daichengxin commented on workflows/quantms.nf
>  // Validate input parameters
Got it. What is the name of the parameter to determine whether to run tmt or lfq? `params.quant_method`?

2021-11-07 13:32 UTC, jpfeuffer commented on workflows/quantms.nf
>  // Validate input parameters
Maybe we can infer it from the SDRF? @ypriverol is that possible?

2021-11-07 15:07 UTC, ypriverol commented on workflows/quantms.nf
>  // Validate input parameters
We can infer it from the sdrf or called `quant_method`

2021-11-07 17:16 UTC, jpfeuffer commented on workflows/quantms.nf
>  // Validate input parameters
Ok

2021-11-08 07:54 UTC, ypriverol commented on subworkflows/local/input_check.nf
> +    ch_logs = Channel.empty()
Is this solve @daichengxin ?

2021-11-08 07:54 UTC, ypriverol commented on subworkflows/local/create_input_channel.nf
> +    sdrf_file
Is this solve @daichengxin ?

2021-11-08 07:54 UTC, ypriverol commented on subworkflows/local/file_preparation.nf
> +    mzmls            // channel: [ val(mzml_id), raw/mzml ]
Is this solve @daichengxin ?

2021-11-08 07:55 UTC, ypriverol commented on workflows/quantms.nf
> +    } else{
Is this solve @daichengxin ?

2021-11-08 07:55 UTC, ypriverol commented on workflows/quantms.nf
> +} else if (tocheck.toLowerCase().endsWith("mzml") || tocheck.toLowerCase().endsWith("raw")) {
Is this solve @daichengxin ?

2021-11-08 07:55 UTC, ypriverol commented on nextflow.config
> +    input                      = "foobarbaz"
Is this solve @daichengxin ?

2021-11-08 08:02 UTC, daichengxin commented on subworkflows/local/input_check.nf
> +    ch_logs = Channel.empty()
Yes, Currently we don't emit a log channel for every module. log file is directly saved.

2021-11-08 08:45 UTC, daichengxin commented on workflows/quantms.nf
> +    } else{
Yes.

2021-11-08 08:45 UTC, daichengxin commented on workflows/quantms.nf
> +} else if (tocheck.toLowerCase().endsWith("mzml") || tocheck.toLowerCase().endsWith("raw")) {
Yes

2021-11-08 08:46 UTC, daichengxin commented on nextflow.config
> +    input                      = "foobarbaz"
Yes

2021-11-08 08:46 UTC, daichengxin commented on subworkflows/local/file_preparation.nf
> +    mzmls            // channel: [ val(mzml_id), raw/mzml ]
Yes

2021-11-08 08:46 UTC, daichengxin commented on subworkflows/local/create_input_channel.nf
> +    sdrf_file
Yes

2021-11-08 09:44 UTC, ypriverol approved these changes

2021-11-08 10:32 UTC, merged