fixed multiqc warning and nf-template
bigbio/quantms pull request #331
Opened 2023-12-21 03:35 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2023-12-22 20:04 UTC, ypriverol commented
@jpfeuffer can we move the phospho files to PRIDE FTP.

2023-12-22 20:44 UTC, jpfeuffer commented
I would say put it to wherever is most reliable.

Did you see this: https://github.com/nf-core/quantms/issues/134

Also seems to be related to test data

2023-12-26 07:22 UTC, ypriverol requested changes

2023-12-26 07:22 UTC, ypriverol commented on bin/diann_convert.py
> +        files = list(Path(directory).glob(f"{n}_ms_info.tsv"))
@daichengxin I think is better: 

```
files = list(Path(directory).rglob(f"{n}_ms_info.tsv"))
```

2023-12-27 18:53 UTC, ypriverol approved these changes

2023-12-27 18:53 UTC, merged