add optional ms2rescore step
bigbio/quantms pull request #362
Opened 2024-03-24 10:27 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-03-24 12:37 UTC, jpfeuffer commented
Really cool! Have you tried allowing mokapot as rescoring engine as well?
Currently seems to be unsupported since the mokapot option is missing in the "posterior probabilities" parameter.

2024-03-26 03:25 UTC, daichengxin commented
> Really cool! Have you tried allowing mokapot as rescoring engine as well? Currently seems to be unsupported since the mokapot option is missing in the "posterior probabilities" parameter.

 mokapot was also allowed.

2024-04-07 07:50 UTC, ypriverol approved these changes

2024-04-27 11:24 UTC, ypriverol commented
@daichengxin can you add here some of the details of the current benchmark?

2024-04-28 08:32 UTC, daichengxin commented
Hi all, we did some benchmark for PXD006675 and immunopeptide dataset PXD020620 after adding rescore steps. I tested 4 strategies. search engine is comet

1. percolator for individual run without extra feature
2. percolator for all experiments without extra feature
3. percolator for all experiments with ms2pip feature
4. percolator for all experiments with deeplc and ms2pip feature

The statistics values of figures are from percolator output dir. The figure 1 is from PXD006675. The legend `NoMs2rescore_percolator_individual_run` is strategy 1, legend `NoMs2rescore_percolator_exp_all` is strategy 2,  legend `percolator_ms2pip_all_exp` is strategy 3 and `ms2rescore_all_exp` is  strategy 4. There was no significant difference in re-scoring between the entire experiment and individual runs at 0.01 FDR. But PSM decreased by 0.6% after re-scoring with ms2pip and deeplc feature for whole experiments compared to without extra feature. Then PSM increased by 0.4% after re-scoring without ms2pip and deeplc feature for whole experiments at 0.05 FDR compared to individual run. But PSM decreased by 0.6% after re-scoring with ms2pip and deeplc feature for whole experiments compared to without extra feature.

![PXD006675_ms2rescore_comet](https://github.com/bigbio/quantms/assets/37200167/8cc87fe1-2b54-4aaa-aa60-385baddee6cc)

Soure data of the figure:
[PXD006675_ms2rescore_pc_comet.csv](https://github.com/bigbio/quantms/files/15141144/PXD006675_ms2rescore_pc_comet.csv)

For PXD020620 (A small immunopeptide dataset).
There was no significant difference in re-scoring with/without extra feature between the entire experiment and individual runs. One reason could be that the dataset is too small. Trying to test on PXD019643 larger immunopeptide dataset.
![PXD020620_comet_ms2rescore_exp_all](https://github.com/bigbio/quantms/assets/37200167/146234e0-47a5-4fce-9669-eceabd3081b1)

2024-04-28 16:35 UTC, jonasscheid requested changes
Well done!
I think one key thing is missing: You need to parse the feature_names.tsv properly from ms2rescore to psmfeatureextractor. I think currently they are not parsed properly and Percolator will just ignore them
And don't forget to add the license in the ms2rescore python script ;-)

2024-04-28 16:35 UTC, jonasscheid commented on bin/ms2rescore_cli.py
> +
If you copy the code, make sure you don't forget to copy the the license as well ;-)
https://github.com/nf-core/mhcquant/blob/e0f2ceefa7bb779de35e491593c50c21774aae49/bin/ms2rescore_cli.py#L2C1-L2C48

And we should think of doing an nf-core module out of ms2rescore to keep our modules in sync

2024-04-28 16:35 UTC, jonasscheid commented on conf/modules.config
> +            "--rescoring_engine ${params.posterior_probabilities}",
double check if mokapot is also allowed if you want to use it

2024-04-28 16:35 UTC, jonasscheid commented on modules/local/openms/extractpsmfeatures/main.nf
As far as I can see you don't parse the features properly to the psmfeatureextractor since they are in a tsv file. You need to provide the novel features as a list, see: https://github.com/nf-core/mhcquant/blob/e0f2ceefa7bb779de35e491593c50c21774aae49/modules/local/openms_psmfeatureextractor.nf#L26

2024-04-28 16:35 UTC, jonasscheid commented on workflows/quantms.nf
> +    if (params.id_only | params.posterior_probabilities == "mokapot") {
Mokapot is implemented in MS2rescore only for psm-level-fdr. Make sure you catch that as well. See [issue](https://github.com/compomics/ms2rescore/issues/112)

2024-04-28 16:35 UTC, jonasscheid commented on subworkflows/local/dda_id.nf
> +def comvert_exp_meta(Map meta, value, file_name, sample_map) {
```suggestion
def convert_exp_meta(Map meta, value, file_name, sample_map) {
```

2024-04-28 16:35 UTC, jonasscheid commented on subworkflows/local/dda_id.nf
> +                ch_consensus_input.view()
```suggestion
```

2024-04-28 16:35 UTC, jonasscheid commented on subworkflows/local/dda_id.nf
> +        } else if (params.posterior_probabilities == 'mokapot') {
Also here: works only on psm-fdr-level

2024-04-28 16:49 UTC, ypriverol commented on bin/ms2rescore_cli.py
> +
As soon as we get the idea working and tested with multiple search engines and datasets, we should aim to have a module.

2024-05-06 19:03 UTC, jonasscheid commented
Great stuff! That is what we see as well 😎

2024-05-06 19:07 UTC, jonasscheid commented
>   LuciPhor2 was not able to provide an output. Please set debug >= 4 for additional information.
  Error: File not found (the file 'SF_200217_pPeptideLibrary_pool1_HCDnlETcaD_OT_rep2_consensus_fdr_filter_pep_luciphor.idXML' could not be found)
  What's going wrong with the failing tests here?

2024-05-07 03:37 UTC, daichengxin commented
> > LuciPhor2 was not able to provide an output. Please set debug >= 4 for additional information.
> > Error: File not found (the file 'SF_200217_pPeptideLibrary_pool1_HCDnlETcaD_OT_rep2_consensus_fdr_filter_pep_luciphor.idXML' could not be found)
> > What's going wrong with the failing tests here?

Not enough PSM to accurately model the data in minimal example(<50 PSM). Readjusted pre-filter levels

2024-05-07 05:55 UTC, jpfeuffer commented
And no big improvement for rescoring over all files, right? Good for speed.
Very well done guys.

2024-05-07 05:55 UTC, jpfeuffer approved these changes

2024-05-07 06:10 UTC, daichengxin commented
> And no big improvement for rescoring over all files (vs. per run) right? Good for speed/parallel processing. Very well done guys.

Yes. No major differences between rescoring for independent msrun and the entire experiment in these benchmarking datasets.

2024-05-07 06:30 UTC, jpfeuffer commented
Ideally we should check at some point on a ground truth dataset that both rescoring or rescoring per ms run does not underestimate the FDR.

2024-05-07 09:49 UTC, jonasscheid approved these changes
Looks good 👍🏼 
When mokapot is used, ms2rescore dervies some nice QC plots investigating the FDR assumption @jpfeuffer. That could be a start.

2024-05-07 10:12 UTC, ypriverol commented
Actually, this trigger a nice discussion @daichengxin Did you tested if it will work everything with pmultiqc.

2024-05-07 14:32 UTC, merged