Dev
bigbio/quantms pull request #378
Opened 2024-06-15 08:48 UTC by daichengxin

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/quantms/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the nf-core/quantms _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nf-test test main.nf.test -profile test,docker`).
- [ ] Check for unexpected warnings in debug mode (`nextflow run . -profile debug,test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2024-06-15 18:35 UTC, ypriverol approved these changes

2024-06-16 08:13 UTC, ypriverol requested changes

2024-06-16 08:13 UTC, ypriverol commented on modules/local/ms2rescore/main.nf
> +        --ms2pip_model_dir ${params.ms2pip_model_dir} \\
@daichengxin if you have multiple process, the models will be downloaded multiple times, because it is pointing to a place related with the task? Im wondering if it will be better to have a job that downloads the models before any job into the workflow dir as default? Then all jobs are reused from there?

2024-06-17 06:19 UTC, daichengxin commented on modules/local/ms2rescore/main.nf
> +        --ms2pip_model_dir ${params.ms2pip_model_dir} \\
Yes.  The models files will be downloaded multiple times into work dir of different processes. And the model files are basically the fixed ones. So I provided the parameters to avoid to download multiple times, in a project and for many projects

2024-06-17 06:24 UTC, jpfeuffer commented on modules/local/ms2rescore/main.nf
> +        --ms2pip_model_dir ${params.ms2pip_model_dir} \\
Cool! How big are the model files by the way? Roughly?

2024-06-17 06:26 UTC, daichengxin commented on modules/local/ms2rescore/main.nf
> +        --ms2pip_model_dir ${params.ms2pip_model_dir} \\
About 1G.

2024-06-17 06:53 UTC, timosachsenberg commented on modules/local/ms2rescore/main.nf
> +        --ms2pip_model_dir ${params.ms2pip_model_dir} \\
Cool addition!

2024-06-17 08:09 UTC, ypriverol approved these changes

2024-06-17 08:20 UTC, timosachsenberg approved these changes

2024-06-17 08:20 UTC, timosachsenberg commented on subworkflows/local/dda_id.nf
> +                position = file(file_name).name.lastIndexOf('_sage_ms2rescore.idXML')
why does sage not have the _feat extension like comet and msgf?

2024-06-17 08:35 UTC, merged